[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
genuinegrads = "J66NdjPnpQWkm3Pj3AihkU4XFjLaV9RF5vz2RUEwKSZF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
# Pull accounts/programs from devnet into your local test validator.
url = "https://api.devnet.solana.com"

# ðŸ‘‡ Replace the addresses with the Base58 values from your node script (see below).
clone = [
  { address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY" },    # mpl-bubblegum
  { address = "mcmt6YrQEMKw8Mw43FmpRLmf7BqRnFMKmAcbxE3xkAW" },     # spl-account-compression
  { address = "mnoopTCrg4p8ry25e4bcWA9XZjbNjMTfgYVGGEdRsf3" },     # spl-noop
  { address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d" }     # mpl-core
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

#dep prog J66NdjPnpQWkm3Pj3AihkU4XFjLaV9RF5vz2RUEwKSZF


